Spike gt
DavisWeimer/futbol_mod1 pull request #6
Opened 2023-06-07 23:30 UTC by Gabe-Torres

Created stat tracker spec file 
Required files in spec helper
Renamed files in futbol

2023-06-07 23:46 UTC, DavisWeimer requested changes
Looks good. Since we changed the file names, let's update the file path names as well in the spec_helper and stat_tracker_spec.

2023-06-07 23:48 UTC, DavisWeimer commented on spec/spec_helper.rb
>  SimpleCov.start
SimpleCov.start should move up to rb:1.5 (line 2)

2023-06-07 23:54 UTC, DavisWeimer approved these changes
Awesome! Looks grand!

2023-06-07 23:55 UTC, kcockett approved these changes
Looks good.

2023-06-07 23:55 UTC, merged

2023-06-08 12:02 UTC, WZale commented on spec/stat_tracker_spec.rb
> +
This looks like a great start for our RSpec tests!

2023-06-08 12:11 UTC, WZale commented
Good call on renaming the class files, too. I'm glad you caught my mistake there, and that we'll be sticking to Ruby convention!